name: CI

on:
  push:
    branches: [ main, dev, beta ]
  pull_request:
    branches: [ main, dev, beta ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        ruby: [2.5, 2.6, 2.7, 3.0]
        exclude:
          - os: windows-latest
            ruby: 3.0
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: bundle install
    - name: Run tests
      run: bundle exec rake spec
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
